name: gha-allure-report-branch-action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Compile binaries
        run: mvn compile
          
  automation:
    name: "Automation"
    runs-on: ubuntu-latest
    needs: [ "build" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Run automation tests
        run: mvn test

      #- name: Switch to 'gh-pages' branch   # switch to a different branch
      #  run: |
      #    git fetch         # fetch all branch info
      #    git checkout gh-pages   # change to desired branch

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        if: always()
        continue-on-error: false
        with:
          ref: gh-pages # branch name
          path: gh-pages-dir # checkout path
  
      - name: Allure Report Action
        uses: epam-zakharenka-dzmitry/allure-report-branch-action@main
        if: always()
        continue-on-error: false
        id: allure
        with:
          report_id: 'allure'
          gh_pages: 'gh-pages-dir'
          report_dir: 'allure-results'
          list_dirs: true
  
      - name: Git Commit and Push Action
        uses: mgrybyk/git-commit-pull-push-action@v1
        if: always()
        with:
          repository: gh-pages-dir
          branch: gh-pages
