name: gha-allure-report-branch-action

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checking out gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run Tests with Maven
      run: mvn -B test --file pom.xml

    - name: Publish Allure Report
      uses: mgrybyk/allure-report-branch-action@v1
      with:
        allure_results: allure-results

    - name: Git Commit and Push Action
      uses: mgrybyk/git-commit-pull-push-action@v1
      if: always()
      with:
        branch: gh-pages
        pull_args: --rebase -X ours
