name: gha-allure-report-branch-action

on:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
  contents: write
  # required by https://github.com/thollander/actions-comment-pull-request
  pull-requests: write

# Allow only one job per PR or branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true # cancel jobs in progress

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Compile binaries
        run: mvn compile
          
  automation:
    name: "Automation"
    runs-on: ubuntu-latest
    needs: [ "build" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Run automation tests
        run: mvn test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: mgrybyk/allure-report-branch-action@v1
        if: always()
        continue-on-error: true
        id: allure # used in comment to PR
        with:
          report_id: 'self-test'
          gh_pages: 'gh-pages'
          report_dir: 'allure-results'
    
      - name: Git Commit and Push Action
        uses: mgrybyk/git-commit-pull-push-action@v1
        if: always()
        with:
          repository: gh-pages
          branch: gh-pages
          pull_args: --rebase -X ours
